### ISSUE TITLE
Error when selecting DeCiv in rulesets, unciv 4.1.0

### ISSUE THREAD

**Issue by carriontrooper** [SpacedOutChicken/DeCiv-Redux#59]
Error log:

**Platform:** Desktop
**Version:** 4.1.0
**Rulesets:** [Policy mod, Victoria II Music, Beliefs_Plus, Warfare Expanded Unciv Bucketeer, Brave New World, UnCiv Vanilla Music Pack, DeCiv Redux, Extra Buildings, Elysium for DeCiv Redux, Drug mod, More Luxuries, Pix5 Tileset, Borneo Civilization, Civ V - Vanilla, Additional Music Ambient, Indonesian Kingdoms, LOTR nab everything new, Civ style set by Bucketeer, Resourceplus, Resource Recyclers, Civ6 mod, Endless Unciv, Dreams of Steam, Alpha Frontier, Future Expansion, Project PMC, Smoky Skies Redux, Expanded Warfare, Civ V - Gods & Kings, Project Paddy Field, Bubbly Borders Example, Closer Cities Distance of 1, Additional Music Various, Fantasia]
**Last Screen:** `com.unciv.ui.newgamescreen.NewGameScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
java.lang.RuntimeException: Actor: TranslatedSelectBox
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:228)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$1.fireChangeEvent(SelectBox.java:71)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.choose(Selection.java:53)
	at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.choose(ArraySelection.java:24)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$SelectBoxScrollPane$1.clicked(SelectBox.java:448)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.crashhandling.CrashHandlingStage.access$touchUp$s80204510(CrashHandlingStage.kt:10)
	at com.unciv.ui.crashhandling.CrashHandlingStage$touchUp$1.invoke(CrashHandlingStage.kt:24)
	at com.unciv.ui.crashhandling.CrashHandlingStage$touchUp$1.invoke(CrashHandlingStage.kt:24)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandling$1.invoke(ExtensionFunctions.kt:333)
	at com.unciv.ui.crashhandling.CrashHandlingStage.touchUp(CrashHandlingStage.kt:24)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:63)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: mods/DeCiv Redux/game.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:190)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:101)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:122)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.load(TextureAtlas.java:87)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:80)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:76)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:71)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:61)
	at com.unciv.ui.images.ImageGetter.loadModAtlases(ImageGetter.kt:93)
	at com.unciv.ui.images.ImageGetter.setNewRuleset(ImageGetter.kt:73)
	at com.unciv.ui.newgamescreen.GameOptionsTable.reloadRuleset(GameOptionsTable.kt:260)
	at com.unciv.ui.newgamescreen.GameOptionsTable.onChooseMod(GameOptionsTable.kt:273)
	at com.unciv.ui.newgamescreen.GameOptionsTable.access$onChooseMod(GameOptionsTable.kt:16)
	at com.unciv.ui.newgamescreen.GameOptionsTable$addBaseRulesetSelectBox$1.invoke(GameOptionsTable.kt:190)
	at com.unciv.ui.newgamescreen.GameOptionsTable$addBaseRulesetSelectBox$1.invoke(GameOptionsTable.kt:172)
	at com.unciv.ui.newgamescreen.GameOptionsTable$addSelectBox$1.invoke(GameOptionsTable.kt:156)
	at com.unciv.ui.newgamescreen.GameOptionsTable$addSelectBox$1.invoke(GameOptionsTable.kt:155)
	at com.unciv.ui.utils.ExtensionFunctionsKt$onChange$1.changed(ExtensionFunctions.kt:89)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 20 more
Caused by: java.io.IOException: Error loading pixmap: Image not of any known type, or corrupt
	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<init>(Gdx2DPixmap.java:85)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:188)
	... 39 more

```

**Comment by carriontrooper** [comment]
Works again in current version
